[package]
name = "traproot-bdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

lightning = { version = "0.0.106", features = ["max_level_trace"] }
lightning-persister = { version = "0.0.106" }
# bdk={version="0.18.0"}
miniscript={version="7.0.0"}
# lightning = "0.0.105"
bitcoin={version="^0.28.0",features=["rand","std"]}

bdk={git="https://github.com/bitcoindevkit/bdk.git"}
# bitcoin={git="https://github.com/rust-bitcoin/rust-bitcoin.git",features=["rand"] }

predicates = "2.1.1"
# [dependencies.electrum-client]
electrum-client={version="0.10.0"}

# [patch.crates-io]
# bitcoin = { git = 'https://github.com/rust-bitcoin/rust-bitcoin.git' }
# rand= "0.8.5"

# electrum-client = "0.9.0"