[package]
name = "traproot-bdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# lightning = { version = "0.0.111", features = ["max_level_trace"] }
# lightning-persister = { version = "0.0.111" }


#   # Add the following dependencies to your cargo.toml and replace {"0.0.110"} with the version number you want to use.

#   lightning-block-sync = { version =  "0.0.111" }
#   lightning-invoice = { version =  "0.19.0"  }
#   lightning-net-tokio = { version = "0.0.111" }
#   lightning-background-processor = { version = "0.0.111" }
#   lightning-rapid-gossip-sync = { version = "0.0.111" }



miniscript={version="8.0.0"}
lightning = "0.0.112"
bitcoin={ version = "0.29.1", features=["rand","std"]}
bitcoin_hashes = { version = "0.11.0", default-features = false }
# bdk={version="0.22.0"}

# [dependencies.electrum-client]
# electrum-client={version="0.10.0"}
electrum-client = "0.12.0"
# serde = { version = "1.0.137", features = ["derive"] }
# bincode = "1.3.3"
# bitcoin_hashes = "0.11.0"
# serde_json="1.0.82"
# either = "1.7.0"
# # [patch.crates-io]
# # bitcoin = { git = 'https://github.com/rust-bitcoin/rust-bitcoin.git' }
# # rand= "0.8.5"

bitcoincore-rpc = "0.16.0"
# # electrum-client = "0.9.0"
# schnorr_fun = "0.7"
# sha2 = "0.10.5"


protobuf = "3.2.0"
futures = "0.3.25"
futures-cpupool = "0.1"
httpbis = "0.9.1"
grpc = "0.8.3"
tls-api = "0.9.0"
tls-api-native-tls = "0.9.0"
bytes = "1.2.1"
rustls = "0.20.7"
hyper-rustls = "0.23.1"
hyper = "0.14.23"
tokio = "1.22.0"
[build-dependencies]
protoc-rust-grpc = "0.8.3"