[package]
name = "traproot-bdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

lightning = { version = "0.0.110", features = ["max_level_trace"] }
lightning-persister = { version = "0.0.110" }
# bdk={version="0.18.0"}
miniscript={version="7.0.0"}
# lightning = "0.0.105"
bitcoin={ version = "0.28.1", features=["rand","std"]}

bdk={version="0.21.0"}
# bitcoin={git="https://github.com/rust-bitcoin/rust-bitcoin.git",features=["rand"] }

# [dependencies.electrum-client]
# electrum-client={version="0.10.0"}
electrum-client = "0.10.2"
serde = { version = "1.0.137", features = ["derive"] }
bincode = "1.3.3"
bitcoin_hashes = "0.11.0"
serde_json="1.0.82"
either = "1.7.0"
# [patch.crates-io]
# bitcoin = { git = 'https://github.com/rust-bitcoin/rust-bitcoin.git' }
# rand= "0.8.5"
bitcoincore-rpc = "0.15.0"
# electrum-client = "0.9.0"