[package]
name = "traproot-bdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

lightning = { version = "0.0.106", features = ["max_level_trace"] }
lightning-persister = { version = "0.0.106" }
# bdk={version="0.17.0"}
miniscript={version="6.0.1"}
# lightning = "0.0.105"
# bitcoin="0.27.1"

bdk={git="https://github.com/bitcoindevkit/bdk.git"}
bitcoin={git="https://github.com/rust-bitcoin/rust-bitcoin.git",features=["rand"] }


# [dependencies.electrum-client]
electrum-client={version="0.9.0"}

[patch.crates-io]
bitcoin = { git = 'https://github.com/rust-bitcoin/rust-bitcoin.git' }
# rand= "0.8.5"

# electrum-client = "0.9.0"